### ISSUE TITLE
unknown property 'TextScanner_AdMobAppId'

### ISSUE THREAD

**Issue by Parag777** [testica/text-scanner#10]
when i open with android studio it get error 
"Could not get unknown property 'TextScanner_AdMobAppId' for BuildType_Decorated{name=release, debuggable=false, testCoverageEnabled=false, jniDebuggable=false, pseudoLocalesEnabled=false, renderscriptDebuggable=false, renderscriptOptimLevel=3, minifyEnabled=true, zipAlignEnabled=true, signingConfig=null, embedMicroApp=true, mBuildConfigFields={}, mResValues={}, mProguardFiles=[F:\androd studio\text-scanner-master\build\intermediates\proguard-files\proguard-android.txt-3.2.1, F:\androd studio\text-scanner-master\app\proguard-rules.pro], mConsumerProguardFiles=[], mManifestPlaceholders={}} of type com.android.build.gradle.internal.dsl.BuildType.
"

**Comment by testica** [comment]
Hey @Parag777
You are missing some keys inside gradle.properties, check it out to learn more https://github.com/testica/text-scanner/pull/8

A quick fix is adding required keys:
- TextScanner_AdMobAppId
`echo "TextScanner_AdMobAppId=\"\"" >> ~/.gradle/gradle.properties`

- TextScanner_AdMobUnitId
`echo "TextScanner_AdMobUnitId=\"\"" >> ~/.gradle/gradle.properties`

**Comment by Parag777** [comment]
> Hey @Parag777
> You are missing some keys inside gradle.properties, check it out to learn more #8
> 
> A quick fix is adding required keys:
> 
> * TextScanner_AdMobAppId
>   `echo "TextScanner_AdMobAppId=\"\"" >> ~/.gradle/gradle.properties`
> * TextScanner_AdMobUnitId
>   `echo "TextScanner_AdMobUnitId=\"\"" >> ~/.gradle/gradle.properties`

But where to add then can u please specify because i am in learning stage

**Comment by testica** [comment]
@Parag777 if you are in linux, run those shell commands
