### ISSUE TITLE
json file missing

### ISSUE THREAD

**Issue by Thamizh-Sterio** [testica/text-scanner#11]
File google-services.json is missing. The Google Services Plugin cannot function without it.

**Comment by testica** [comment]
I don't think is a good idea to share my `google-services.json`.
I am thinking in two alternatives:
- Make a fake google-services.json, but I don't know the behaviour of this.
- Remove google integrations.

Whatever, I will search for a "right" solution for this case.
Any suggestion @Thamizh-Sterio  ?

**Comment by Thamizh-Sterio** [comment]
> I don't think is a good idea to share my `google-services.json`.
> I am thinking in two alternatives:
> 
> * Make a fake google-services.json, but I don't know the behaviour of this.
> * Remove google integrations.
> 
> Whatever, I will search for a "right" solution for this case.
> Any suggestion @Thamizh-Sterio ?

removing google integration will affect in the app?

**Comment by testica** [comment]
For development purposes, no.

In readme.md I point that:
> firebase: to report metrics (for development purpose, you can remove firebase dependencies or add your own google-services.json).
> admob: to show google ads (to pay some bills). Check PR #8 to know more about admob environment.

But, It is necessary for release version.

**Comment by Thamizh-Sterio** [comment]
> For development purposes, no.
> 
> In readme.md I point that:
> 
> > firebase: to report metrics (for development purpose, you can remove firebase dependencies or add your own google-services.json).
> > admob: to show google ads (to pay some bills). Check PR #8 to know more about admob environment.
> 
> But, It is necessary for release version.

Thanks @testica i build it by removing google integration
