### ISSUE TITLE
App crashes on screen rotation after cropping the image

### ISSUE THREAD

**Issue by neupanedipen** [testica/text-scanner#3]
#### Expected behavior<br>
The app is supposed to be stable during screen rotation after cropping the image.<br>
#### Actual behavior<br>
But the app crashes when I change the screen orientation after cropping the image.<br>
#### How to reproduce<br>
1. Install the app.<br>
2. Launch the app.<br>
3. Click on camera option to upload and image and choose an image from your device gallery.<br>
4. Now crop the image to the desired dimensions and click on tick&nbsp; option.<br>
5. Now change the screen orientation to landscape mode.<br>
The app crashes.<br>
* App Version: 1.0<br>
* Device: Samsung Galaxy J5<br>
* Operating System: Android 6.0.1<br>
#### Recording Of The Bug<br>
https://youtu.be/eoCXdCa03LE

**Comment by testica** [comment]
Thank you for the issue @neupanedipen and sorry for the late. Yes, when device orientation changes the app will crash. I hope to fix soon.
